[project]
authors = ["Wytamma Wirth <wytamma.wirth@me.com>"]
channels = ["conda-forge", "bioconda"]
name = "barbet"
platforms = ["linux-64", "linux-aarch64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
prodigal = ">=2.6.3,<3"
hmmer = ">=3.4,<4"
